### ISSUE TITLE
Can't load from istream anymore

### ISSUE THREAD

**Issue by skalleAnka** [cppfw/svgdom#41]
Hi

I am on vacation so working with my games again ;)

After updating svgren, svgdom and all of the dependencies from NuGet, it seems svgdom can't load any svg file from an istream. This code always produces exception mikroxml::malformed_xml with message "Unexpected '/' character in attribute list encountered. line: 1" 

`
std::ifstream ist;
ist.open(filename);
auto dom = svgdom::load(ist);
`
Not a big issue for me right now as it seems to work if I use papki::fs_file instead, but thought I would report it anyway. :)

**Comment by igagis** [comment]
Thanks for report! I'll have a look.

**Comment by igagis** [comment]
@skalleAnka could you attach a sample SVG file which fails for you?

**Comment by igagis** [comment]
never mind, I reproduced it with `tiger.svg`

**Comment by igagis** [comment]
The problem is fixed in `svgdom` version `0.3.71`. Please update and try.

**Comment by skalleAnka** [comment]
I can confirm that it does work in 0.3.71.

Thank you!
