### ISSUE TITLE
MSVS v143 support

### ISSUE THREAD

**Issue by John-By** [cppfw/svgdom#43]
Please add support for the latest msvs v143 build tools.

**Comment by igagis** [comment]
I'm waiting for this compiler bug to be fixed before adding `v143` tools support:
https://developercommunity.visualstudio.com/t/error-MSB6006:-CLexe-exited-with-code/10045045?viewtype=all

**Comment by igagis** [comment]
the issue is resolved, I'll start working on `143` support

**Comment by igagis** [comment]
done!
update to latest versions of nuget packages and there will be v143 support!

**Comment by John-By** [comment]
Thanks for the update!
