### ISSUE TITLE
Errors when using it in a project in windows

### ISSUE THREAD

**Issue by ElCapor** [cppfw/svgdom#45]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2555	'svgdom::use_element::get_tag': overriding virtual function return type differs and is not covariant from 'cssom::styleable::get_tag' (compiling source file src\GUI.cpp)	ImGui DX11 base	C:\Users\HP\Desktop\ImGuiDX11base-main\packages\libsvgdom.0.4.10\build\native\include\svgdom\elements\structurals.hpp	93	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2555	'svgdom::use_element::get_id': overriding virtual function return type differs and is not covariant from 'cssom::styleable::get_id' (compiling source file src\GUI.cpp)	ImGui DX11 base	C:\Users\HP\Desktop\ImGuiDX11base-main\packages\libsvgdom.0.4.10\build\native\include\svgdom\elements\structurals.hpp	86	

i get this error 9 times in my output console when building.

I installed svgdom through nuget
im using v143 , c++17
thanks for help in advance

**Comment by igagis** [comment]
@ElCapor 

I see that you have installed version `0.4.10` of the package `libsvgdom`. Could you check, what is the version of `libcssom` package?

**Comment by igagis** [comment]
closing due to no response from submitter
